language: ruby
rvm:
  - 2.2.2
services:
  - redis-server
cache: bundler
bundler_args: --without production
before_script:
  - bundle exec rake db:create db:migrate RAILS_ENV=test
script:
  - bundle exec rspec spec
